/home/jiaoxiaolu_org/software/eems/runeems_snps/src/runeems_snps --params params-chain1.ini --seed 123 
/home/jiaoxiaolu_org/software/eems/runeems_snps/src/runeems_snps --params params-chain2.ini --seed 234 
/home/jiaoxiaolu_org/software/eems/runeems_snps/src/runeems_snps --params params-chain3.ini --seed 345 
/home/jiaoxiaolu_org/software/eems/runeems_snps/src/runeems_snps --params params-chain4.ini --seed 456 
/home/jiaoxiaolu_org/software/eems/runeems_snps/src/runeems_snps --params params-chain5.ini --seed 567 
/home/jiaoxiaolu_org/software/eems/runeems_snps/src/runeems_snps --params params-chain6.ini --seed 678 
/home/jiaoxiaolu_org/software/eems/runeems_snps/src/runeems_snps --params params-chain7.ini --seed 789 
/home/jiaoxiaolu_org/software/eems/runeems_snps/src/runeems_snps --params params-chain8.ini --seed 890 
/home/jiaoxiaolu_org/software/eems/runeems_snps/src/runeems_snps --params params-chain9.ini --seed 901 
/home/jiaoxiaolu_org/software/eems/runeems_snps/src/runeems_snps --params params-chain10.ini --seed 012 
